---
skip_tags: true

skip_commits:
  files:
    - '*.md'
    - '*.yml.default'
  message: /\[minor\]/

image: Ubuntu1804-minimal

matrix:
  fast_finish: false

# to disable automatic builds
build: off

environment:
  CLOUDBOX_BRANCH: "master"
  CLOUDBOX_PATH: "/home/appveyor/cloudbox"
  COMMUNITY_PATH: "/home/appveyor/projects/community"
  TAGS: >
    
    
    
    
    apprise
    archivebox
    asshama
    autoscan
    bazarrx
    beets
    bitwarden
    bookstack
    btrfsmaintenance
    calibre
    calibre-web
    comicstreamer
    couchpotato
    coder
    comixed
    deemix
    deemixrr
    deezloader-remix
    deluge
    delugevpn
    embystat
    emby2
    epms
    filebot
    filezilla
    flaresolverr
    funkwhale
    gazee
    glances
    goplaxt
    grafana
    handbrake
    healthchecks
    heimdall
    influxdb
    invoiceninja
    jdownloader2
    jellyfin
    jirafeau
    kitana
    komga
    lazylibrarian
    lidarrx
    logarr
    mediabutler
    medusa
    minecraft
    monitorr
    mylar
    mylar3
    navidrome
    nextcloud
    nowshowing
    nzbhydra
    ombix
    organizrv1
    ouroboros
    overseerr
    plex2
    pyload
    qbittorrent
    qbittorrentvpn
    quassel
    radarrx
    redbot
    resilio-sync
    requestrrx
    rocketchat
    sickchill
    sonarrx
    speedtest
    sshwifty
    stash
    subsonic
    synclounge
    tdarr
    telegraf
    thelounge
    transmissionvpn
    transmissionx
    ubooquity
    unifi
    unmanic
    varken
    vnstat
    watchtower
    wallabag
    wordpress
    xteve
    znc
  matrix:

  - job_name: airdcpp

  - job_name: airsonic

  - job_name: alltube

  - job_name: alternatrr

  - job_name: alternatrrx

  - job_name: amongus

for:

  -
    matrix:
      only:
        - job_name: airdcpp

    environment:
      TAG: airdcpp

    build_script:
    - sh: curl -s https://raw.githubusercontent.com/saltydk/AppveyorTest/main/test.sh | bash

  -
    matrix:
      only:
        - job_name: airsonic

    environment:
      TAG: airsonic

    build_script:
    - sh: curl -s https://raw.githubusercontent.com/saltydk/AppveyorTest/main/test.sh | bash

  -
    matrix:
      only:
        - job_name: alltube

    environment:
      TAG: alltube

    build_script:
    - sh: curl -s https://raw.githubusercontent.com/saltydk/AppveyorTest/main/test.sh | bash

  -
    matrix:
      only:
        - job_name: alternatrr

    environment:
      TAG: alternatrr

    build_script:
    - sh: curl -s https://raw.githubusercontent.com/saltydk/AppveyorTest/main/test.sh | bash

  -
    matrix:
      only:
        - job_name: alternatrrx

    environment:
      TAG: alternatrrx

    build_script:
    - sh: curl -s https://raw.githubusercontent.com/saltydk/AppveyorTest/main/test.sh | bash

  -
    matrix:
      only:
        - job_name: amongus

    environment:
      TAG: amongus

    build_script:
    - sh: curl -s https://raw.githubusercontent.com/saltydk/AppveyorTest/main/test.sh | bash
